version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
    commands:
      - pip3 install boto3
  build:
    commands:
      - temp_role=$(aws sts assume-role --role-arn $LAMBDA_PUBLISHING_ROLE --role-session-name "codebuild-lambda-layer")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
      - echo ">>>>> Beginning build of subdirectories >>>>>"
      - bash build.sh $TEAM_NAME
      - echo ">>>>> Beginning build of default layer >>>>>"
      - ls && echo "-----> making temporary directory"
      - mkdir -p layer/python
      - pip3 -q install -r ./requirements.txt -t layer/python
      - cd layer/
      - zip -r layer.zip python/ -x \*__pycache__\*
      - echo "Uploading default Lambda Layer..."
      - layer=$(aws lambda publish-layer-version --layer-name sdlf-$TEAM_NAME-$LAYER_NAME --description "Contains a default Pip library layer" --compatible-runtimes "python3.6" "python3.7" --zip-file fileb://./layer.zip)
      - latest_layer_version=$(echo $layer | jq -r .LayerVersionArn)
      - aws ssm put-parameter --name "/SDLF/Lambda/$TEAM_NAME/LatestDefaultPipLibraryLayer" --value $latest_layer_version --type String --overwrite
