version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
    commands:
      - pip3 install boto3
  build:
    commands:
      - account_id=$(aws sts get-caller-identity | jq .Account)
      - temp_role=$(aws sts assume-role --role-arn $LAMBDA_PUBLISHING_ROLE --role-session-name "codebuild-lambda-layer")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
      - cd ./python/datalake_library/transforms/
      - python3 ./dataset_mappings.py $TEAM_NAME $ENV_NAME
artifacts:
  files:
    - '*'
    - '**/*'
